[package]
name = "job-queue"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
fastrand = "2.3.0"
rayon = "1.10.0"
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.15"
